package co.com.app.homerepair.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import co.com.app.homerepair.model.Categoria;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CATEGORIA".
*/
public class CategoriaDao extends AbstractDao<Categoria, Long> {

    public static final String TABLENAME = "CATEGORIA";

    /**
     * Properties of entity Categoria.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Cat_descripcion = new Property(1, String.class, "cat_descripcion", false, "CAT_DESCRIPCION");
        public final static Property Cat_estado = new Property(2, String.class, "cat_estado", false, "CAT_ESTADO");
    }

    private DaoSession daoSession;


    public CategoriaDao(DaoConfig config) {
        super(config);
    }
    
    public CategoriaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CATEGORIA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"CAT_DESCRIPCION\" TEXT," + // 1: cat_descripcion
                "\"CAT_ESTADO\" TEXT);"); // 2: cat_estado
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CATEGORIA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Categoria entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String cat_descripcion = entity.getCat_descripcion();
        if (cat_descripcion != null) {
            stmt.bindString(2, cat_descripcion);
        }
 
        String cat_estado = entity.getCat_estado();
        if (cat_estado != null) {
            stmt.bindString(3, cat_estado);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Categoria entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String cat_descripcion = entity.getCat_descripcion();
        if (cat_descripcion != null) {
            stmt.bindString(2, cat_descripcion);
        }
 
        String cat_estado = entity.getCat_estado();
        if (cat_estado != null) {
            stmt.bindString(3, cat_estado);
        }
    }

    @Override
    protected final void attachEntity(Categoria entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Categoria readEntity(Cursor cursor, int offset) {
        Categoria entity = new Categoria( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // cat_descripcion
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // cat_estado
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Categoria entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCat_descripcion(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCat_estado(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Categoria entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Categoria entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Categoria entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
