package co.com.app.homerepair.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import co.com.app.homerepair.model.Solicitud;
import co.com.app.homerepair.model.Usuarios;

import co.com.app.homerepair.model.Comentario;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COMENTARIO".
*/
public class ComentarioDao extends AbstractDao<Comentario, Long> {

    public static final String TABLENAME = "COMENTARIO";

    /**
     * Properties of entity Comentario.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Ctrio_descripcion = new Property(1, String.class, "ctrio_descripcion", false, "CTRIO_DESCRIPCION");
        public final static Property Ctrio_sol_id = new Property(2, Long.class, "ctrio_sol_id", false, "CTRIO_SOL_ID");
        public final static Property Ctrio_usu_id = new Property(3, Long.class, "ctrio_usu_id", false, "CTRIO_USU_ID");
    }

    private DaoSession daoSession;

    private Query<Comentario> solicitud_ComentariosQuery;
    private Query<Comentario> usuarios_ComentarioQuery;

    public ComentarioDao(DaoConfig config) {
        super(config);
    }
    
    public ComentarioDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COMENTARIO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CTRIO_DESCRIPCION\" TEXT," + // 1: ctrio_descripcion
                "\"CTRIO_SOL_ID\" INTEGER," + // 2: ctrio_sol_id
                "\"CTRIO_USU_ID\" INTEGER);"); // 3: ctrio_usu_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COMENTARIO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Comentario entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String ctrio_descripcion = entity.getCtrio_descripcion();
        if (ctrio_descripcion != null) {
            stmt.bindString(2, ctrio_descripcion);
        }
 
        Long ctrio_sol_id = entity.getCtrio_sol_id();
        if (ctrio_sol_id != null) {
            stmt.bindLong(3, ctrio_sol_id);
        }
 
        Long ctrio_usu_id = entity.getCtrio_usu_id();
        if (ctrio_usu_id != null) {
            stmt.bindLong(4, ctrio_usu_id);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Comentario entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String ctrio_descripcion = entity.getCtrio_descripcion();
        if (ctrio_descripcion != null) {
            stmt.bindString(2, ctrio_descripcion);
        }
 
        Long ctrio_sol_id = entity.getCtrio_sol_id();
        if (ctrio_sol_id != null) {
            stmt.bindLong(3, ctrio_sol_id);
        }
 
        Long ctrio_usu_id = entity.getCtrio_usu_id();
        if (ctrio_usu_id != null) {
            stmt.bindLong(4, ctrio_usu_id);
        }
    }

    @Override
    protected final void attachEntity(Comentario entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Comentario readEntity(Cursor cursor, int offset) {
        Comentario entity = new Comentario( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // ctrio_descripcion
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // ctrio_sol_id
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // ctrio_usu_id
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Comentario entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCtrio_descripcion(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCtrio_sol_id(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setCtrio_usu_id(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Comentario entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Comentario entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Comentario entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "comentarios" to-many relationship of Solicitud. */
    public List<Comentario> _querySolicitud_Comentarios(Long ctrio_sol_id) {
        synchronized (this) {
            if (solicitud_ComentariosQuery == null) {
                QueryBuilder<Comentario> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Ctrio_sol_id.eq(null));
                solicitud_ComentariosQuery = queryBuilder.build();
            }
        }
        Query<Comentario> query = solicitud_ComentariosQuery.forCurrentThread();
        query.setParameter(0, ctrio_sol_id);
        return query.list();
    }

    /** Internal query to resolve the "comentario" to-many relationship of Usuarios. */
    public List<Comentario> _queryUsuarios_Comentario(Long ctrio_usu_id) {
        synchronized (this) {
            if (usuarios_ComentarioQuery == null) {
                QueryBuilder<Comentario> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Ctrio_usu_id.eq(null));
                usuarios_ComentarioQuery = queryBuilder.build();
            }
        }
        Query<Comentario> query = usuarios_ComentarioQuery.forCurrentThread();
        query.setParameter(0, ctrio_usu_id);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getSolicitudDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getUsuariosDao().getAllColumns());
            builder.append(" FROM COMENTARIO T");
            builder.append(" LEFT JOIN SOLICITUD T0 ON T.\"CTRIO_SOL_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN USUARIOS T1 ON T.\"CTRIO_USU_ID\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Comentario loadCurrentDeep(Cursor cursor, boolean lock) {
        Comentario entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Solicitud solicitud = loadCurrentOther(daoSession.getSolicitudDao(), cursor, offset);
        entity.setSolicitud(solicitud);
        offset += daoSession.getSolicitudDao().getAllColumns().length;

        Usuarios usuarios = loadCurrentOther(daoSession.getUsuariosDao(), cursor, offset);
        entity.setUsuarios(usuarios);

        return entity;    
    }

    public Comentario loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Comentario> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Comentario> list = new ArrayList<Comentario>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Comentario> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Comentario> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
