package co.com.app.homerepair.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import co.com.app.homerepair.model.ActividadEconomica;
import co.com.app.homerepair.model.Adjunto;
import co.com.app.homerepair.model.EstadoSolicitud;
import co.com.app.homerepair.model.Rol;
import co.com.app.homerepair.model.Categoria;
import co.com.app.homerepair.model.Usuarios;
import co.com.app.homerepair.model.Clientes;
import co.com.app.homerepair.model.Proveedor;
import co.com.app.homerepair.model.CategoriaProveedor;
import co.com.app.homerepair.model.Solicitud;
import co.com.app.homerepair.model.Comentario;
import co.com.app.homerepair.model.Cotizacion;
import co.com.app.homerepair.model.AdjuntoSolicitud;

import co.com.app.homerepair.dao.ActividadEconomicaDao;
import co.com.app.homerepair.dao.AdjuntoDao;
import co.com.app.homerepair.dao.EstadoSolicitudDao;
import co.com.app.homerepair.dao.RolDao;
import co.com.app.homerepair.dao.CategoriaDao;
import co.com.app.homerepair.dao.UsuariosDao;
import co.com.app.homerepair.dao.ClientesDao;
import co.com.app.homerepair.dao.ProveedorDao;
import co.com.app.homerepair.dao.CategoriaProveedorDao;
import co.com.app.homerepair.dao.SolicitudDao;
import co.com.app.homerepair.dao.ComentarioDao;
import co.com.app.homerepair.dao.CotizacionDao;
import co.com.app.homerepair.dao.AdjuntoSolicitudDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig actividadEconomicaDaoConfig;
    private final DaoConfig adjuntoDaoConfig;
    private final DaoConfig estadoSolicitudDaoConfig;
    private final DaoConfig rolDaoConfig;
    private final DaoConfig categoriaDaoConfig;
    private final DaoConfig usuariosDaoConfig;
    private final DaoConfig clientesDaoConfig;
    private final DaoConfig proveedorDaoConfig;
    private final DaoConfig categoriaProveedorDaoConfig;
    private final DaoConfig solicitudDaoConfig;
    private final DaoConfig comentarioDaoConfig;
    private final DaoConfig cotizacionDaoConfig;
    private final DaoConfig adjuntoSolicitudDaoConfig;

    private final ActividadEconomicaDao actividadEconomicaDao;
    private final AdjuntoDao adjuntoDao;
    private final EstadoSolicitudDao estadoSolicitudDao;
    private final RolDao rolDao;
    private final CategoriaDao categoriaDao;
    private final UsuariosDao usuariosDao;
    private final ClientesDao clientesDao;
    private final ProveedorDao proveedorDao;
    private final CategoriaProveedorDao categoriaProveedorDao;
    private final SolicitudDao solicitudDao;
    private final ComentarioDao comentarioDao;
    private final CotizacionDao cotizacionDao;
    private final AdjuntoSolicitudDao adjuntoSolicitudDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        actividadEconomicaDaoConfig = daoConfigMap.get(ActividadEconomicaDao.class).clone();
        actividadEconomicaDaoConfig.initIdentityScope(type);

        adjuntoDaoConfig = daoConfigMap.get(AdjuntoDao.class).clone();
        adjuntoDaoConfig.initIdentityScope(type);

        estadoSolicitudDaoConfig = daoConfigMap.get(EstadoSolicitudDao.class).clone();
        estadoSolicitudDaoConfig.initIdentityScope(type);

        rolDaoConfig = daoConfigMap.get(RolDao.class).clone();
        rolDaoConfig.initIdentityScope(type);

        categoriaDaoConfig = daoConfigMap.get(CategoriaDao.class).clone();
        categoriaDaoConfig.initIdentityScope(type);

        usuariosDaoConfig = daoConfigMap.get(UsuariosDao.class).clone();
        usuariosDaoConfig.initIdentityScope(type);

        clientesDaoConfig = daoConfigMap.get(ClientesDao.class).clone();
        clientesDaoConfig.initIdentityScope(type);

        proveedorDaoConfig = daoConfigMap.get(ProveedorDao.class).clone();
        proveedorDaoConfig.initIdentityScope(type);

        categoriaProveedorDaoConfig = daoConfigMap.get(CategoriaProveedorDao.class).clone();
        categoriaProveedorDaoConfig.initIdentityScope(type);

        solicitudDaoConfig = daoConfigMap.get(SolicitudDao.class).clone();
        solicitudDaoConfig.initIdentityScope(type);

        comentarioDaoConfig = daoConfigMap.get(ComentarioDao.class).clone();
        comentarioDaoConfig.initIdentityScope(type);

        cotizacionDaoConfig = daoConfigMap.get(CotizacionDao.class).clone();
        cotizacionDaoConfig.initIdentityScope(type);

        adjuntoSolicitudDaoConfig = daoConfigMap.get(AdjuntoSolicitudDao.class).clone();
        adjuntoSolicitudDaoConfig.initIdentityScope(type);

        actividadEconomicaDao = new ActividadEconomicaDao(actividadEconomicaDaoConfig, this);
        adjuntoDao = new AdjuntoDao(adjuntoDaoConfig, this);
        estadoSolicitudDao = new EstadoSolicitudDao(estadoSolicitudDaoConfig, this);
        rolDao = new RolDao(rolDaoConfig, this);
        categoriaDao = new CategoriaDao(categoriaDaoConfig, this);
        usuariosDao = new UsuariosDao(usuariosDaoConfig, this);
        clientesDao = new ClientesDao(clientesDaoConfig, this);
        proveedorDao = new ProveedorDao(proveedorDaoConfig, this);
        categoriaProveedorDao = new CategoriaProveedorDao(categoriaProveedorDaoConfig, this);
        solicitudDao = new SolicitudDao(solicitudDaoConfig, this);
        comentarioDao = new ComentarioDao(comentarioDaoConfig, this);
        cotizacionDao = new CotizacionDao(cotizacionDaoConfig, this);
        adjuntoSolicitudDao = new AdjuntoSolicitudDao(adjuntoSolicitudDaoConfig, this);

        registerDao(ActividadEconomica.class, actividadEconomicaDao);
        registerDao(Adjunto.class, adjuntoDao);
        registerDao(EstadoSolicitud.class, estadoSolicitudDao);
        registerDao(Rol.class, rolDao);
        registerDao(Categoria.class, categoriaDao);
        registerDao(Usuarios.class, usuariosDao);
        registerDao(Clientes.class, clientesDao);
        registerDao(Proveedor.class, proveedorDao);
        registerDao(CategoriaProveedor.class, categoriaProveedorDao);
        registerDao(Solicitud.class, solicitudDao);
        registerDao(Comentario.class, comentarioDao);
        registerDao(Cotizacion.class, cotizacionDao);
        registerDao(AdjuntoSolicitud.class, adjuntoSolicitudDao);
    }
    
    public void clear() {
        actividadEconomicaDaoConfig.clearIdentityScope();
        adjuntoDaoConfig.clearIdentityScope();
        estadoSolicitudDaoConfig.clearIdentityScope();
        rolDaoConfig.clearIdentityScope();
        categoriaDaoConfig.clearIdentityScope();
        usuariosDaoConfig.clearIdentityScope();
        clientesDaoConfig.clearIdentityScope();
        proveedorDaoConfig.clearIdentityScope();
        categoriaProveedorDaoConfig.clearIdentityScope();
        solicitudDaoConfig.clearIdentityScope();
        comentarioDaoConfig.clearIdentityScope();
        cotizacionDaoConfig.clearIdentityScope();
        adjuntoSolicitudDaoConfig.clearIdentityScope();
    }

    public ActividadEconomicaDao getActividadEconomicaDao() {
        return actividadEconomicaDao;
    }

    public AdjuntoDao getAdjuntoDao() {
        return adjuntoDao;
    }

    public EstadoSolicitudDao getEstadoSolicitudDao() {
        return estadoSolicitudDao;
    }

    public RolDao getRolDao() {
        return rolDao;
    }

    public CategoriaDao getCategoriaDao() {
        return categoriaDao;
    }

    public UsuariosDao getUsuariosDao() {
        return usuariosDao;
    }

    public ClientesDao getClientesDao() {
        return clientesDao;
    }

    public ProveedorDao getProveedorDao() {
        return proveedorDao;
    }

    public CategoriaProveedorDao getCategoriaProveedorDao() {
        return categoriaProveedorDao;
    }

    public SolicitudDao getSolicitudDao() {
        return solicitudDao;
    }

    public ComentarioDao getComentarioDao() {
        return comentarioDao;
    }

    public CotizacionDao getCotizacionDao() {
        return cotizacionDao;
    }

    public AdjuntoSolicitudDao getAdjuntoSolicitudDao() {
        return adjuntoSolicitudDao;
    }

}
