package co.com.app.homerepair.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

import co.com.app.homerepair.model.Rol;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "ROL".
*/
public class RolDao extends AbstractDao<Rol, Long> {

    public static final String TABLENAME = "ROL";

    /**
     * Properties of entity Rol.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Rol_nombre = new Property(1, String.class, "rol_nombre", false, "ROL_NOMBRE");
        public final static Property Rol_estado = new Property(2, String.class, "rol_estado", false, "ROL_ESTADO");
    }

    private DaoSession daoSession;


    public RolDao(DaoConfig config) {
        super(config);
    }
    
    public RolDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ROL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"ROL_NOMBRE\" TEXT," + // 1: rol_nombre
                "\"ROL_ESTADO\" TEXT);"); // 2: rol_estado
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ROL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Rol entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String rol_nombre = entity.getRol_nombre();
        if (rol_nombre != null) {
            stmt.bindString(2, rol_nombre);
        }
 
        String rol_estado = entity.getRol_estado();
        if (rol_estado != null) {
            stmt.bindString(3, rol_estado);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Rol entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String rol_nombre = entity.getRol_nombre();
        if (rol_nombre != null) {
            stmt.bindString(2, rol_nombre);
        }
 
        String rol_estado = entity.getRol_estado();
        if (rol_estado != null) {
            stmt.bindString(3, rol_estado);
        }
    }

    @Override
    protected final void attachEntity(Rol entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Rol readEntity(Cursor cursor, int offset) {
        Rol entity = new Rol( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // rol_nombre
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // rol_estado
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Rol entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRol_nombre(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setRol_estado(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Rol entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Rol entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Rol entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
