package co.com.app.homerepair.model;

import org.greenrobot.greendao.annotation.*;

import java.util.List;
import co.com.app.homerepair.dao.DaoSession;
import org.greenrobot.greendao.DaoException;

import co.com.app.homerepair.dao.ActividadEconomicaDao;
import co.com.app.homerepair.dao.ProveedorDao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "ACTIVIDAD_ECONOMICA".
 */
@Entity(active = true)
public class ActividadEconomica {

    @Id
    private Long id;
    private String ae_descripcion;
    private String ae_estado;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient ActividadEconomicaDao myDao;

    @ToMany(joinProperties = {
        @JoinProperty(name = "id", referencedName = "prov_ae_id")
    })
    private List<Proveedor> proveedores;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public ActividadEconomica() {
    }

    public ActividadEconomica(Long id) {
        this.id = id;
    }

    @Generated
    public ActividadEconomica(Long id, String ae_descripcion, String ae_estado) {
        this.id = id;
        this.ae_descripcion = ae_descripcion;
        this.ae_estado = ae_estado;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getActividadEconomicaDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAe_descripcion() {
        return ae_descripcion;
    }

    public void setAe_descripcion(String ae_descripcion) {
        this.ae_descripcion = ae_descripcion;
    }

    public String getAe_estado() {
        return ae_estado;
    }

    public void setAe_estado(String ae_estado) {
        this.ae_estado = ae_estado;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    @Generated
    public List<Proveedor> getProveedores() {
        if (proveedores == null) {
            __throwIfDetached();
            ProveedorDao targetDao = daoSession.getProveedorDao();
            List<Proveedor> proveedoresNew = targetDao._queryActividadEconomica_Proveedores(id);
            synchronized (this) {
                if(proveedores == null) {
                    proveedores = proveedoresNew;
                }
            }
        }
        return proveedores;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    @Generated
    public synchronized void resetProveedores() {
        proveedores = null;
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
